CREATE DATABASE nopalito;
USE nopalito;

CREATE TABLE usuario(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	correo VARCHAR(100) NOT NULL,
	contraseña VARCHAR(100) NOT NULL 
);

CREATE TABLE lugar(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	codigo_postal MEDIUMINT UNSIGNED NOT NULL,
    municipio VARCHAR(100) NOT NULL,
    colonia VARCHAR(100) NOT NULL,
    calle VARCHAR(100) NOT NULL
    usuarioId INT UNSIGNED NOT NULL,
    FOREIGN KEY (usuarioId) REFERENCES usuario(id)
);

CREATE TABLE arbol(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha DATE NOT NULL,
    especie VARCHAR(100) NOT NULL,
    imagen VARCHAR(1024) NOT NULL,
    lugarId INT UNSIGNED NOT NULL,
    FOREIGN KEY (lugarId) REFERENCES lugar(id)
);